[package]
name    = "optional-dependency"
version = "0.1.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0", optional = true }

[target.'cfg(feature = "serde")'.dependencies]
serde_bytes = "^0.11.3"
